### ISSUE TITLE
info function namespace question

### ISSUE THREAD

**Issue by Biserkov** [uncomplicate/clojurecuda#6]
The info function has been moved to `uncomplicate.commons.core` namespace. But the rest of the info-functions are in the  `uncomplicate.clojurecuda.info` namespace. I see 2 ways to fix this:

- update the tutorials. I can do that.
- add a stub `clojurecuda.info/info` which simply calls `commons.core/info`

**Comment by blueberry** [comment]
This is intended. commons.core/info is a "universal" info function that works with any object from fluokitten, neanderhtal, bayadera, clojurecl, clojurecuda etc. clojurecuda.info contain clojurecuda-specific info functions.

The tutorial should be updated. Do you refer to turorials on the blog, or tutorials on the clojurecuda webpage. The blog tutorials are autogenerated from org files, so there's not much sense in updating the html directly, since this is both tedious and useless since they will be overwritten whenever I update the source org files and regenerate particular blog post.

Maybe a better solution would be to report to me instances of blog posts that are not up to date so I can fix that.

**Comment by Biserkov** [comment]
OK, makes total sense. I meant both. My goal is to make sure that beginners (like myself) don't encounter errors while trying to follow the tutorials. Editing the HTML is indeed a pain I'd like to avoid (and possibly learn org-mode in the process). Do you have the .org files somewhere on GitHub, I couldn't find them.

I'll submit a PR for the markdown guide on the clojurecuda webpage.

**Comment by Biserkov** [comment]
info is used towards the end in Part 3 Context shenanigans

**Comment by blueberry** [comment]
I updated the relevant blog posts. I'll close this issue now, but if you discover anything else, please re-open it.
